### ISSUE TITLE
Mob "lagging"

### ISSUE THREAD

**Issue by watermelon0guy** [xZarex/simple-chunkloader#1]
I am observing a very strange problem and by way of an exception I found out that the problem is in this mod. The game goes smoothly and there are no problems, but for some reason the mobs "lag". They move jerkily as if I have a big ping on the server. All this happens in a single game.

**Comment by xZarex** [comment]
@watermelon0guy 
I'll have a look within the 1.19.1 update.

Are mobs near to you "lagging"?
Is this problem only in chunks which are loaded with a chunkloader or in every chunk?

A short video would be great.

**Comment by watermelon0guy** [comment]
I apologize for such a long answer.
Video with a bug: https://youtu.be/Sdj9N3u3LjE . List of mods: [mods_list.txt](https://github.com/xZarex/simple-chunkloader/files/9229098/mods_list.txt)

**Comment by watermelon0guy** [comment]
Update: When I install at least one loader in the world (even if I broke it right away), everything starts working as it should even if I go out and enter the world.
But I think it's still worth taking a look at what the problem is. I'll put the mod on the server and see how it behaves there
